// <auto-generated />
using System;
using LivrariaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LivrariaAPI.Migrations
{
    [DbContext(typeof(LivrariaAPIContext))]
    [Migration("20210531025804_DBInit")]
    partial class DBInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("LivrariaAPI.Model.Book", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("editorid")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.Property<int>("pages")
                        .HasColumnType("int");

                    b.Property<decimal>("value")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id");

                    b.HasIndex("editorid");

                    b.ToTable("book");
                });

            modelBuilder.Entity("LivrariaAPI.Model.Person", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("address")
                        .HasColumnType("longtext");

                    b.Property<string>("firstName")
                        .HasColumnType("longtext");

                    b.Property<string>("gender")
                        .HasColumnType("longtext");

                    b.Property<string>("lastName")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("person");
                });

            modelBuilder.Entity("LivrariaAPI.Model.Book", b =>
                {
                    b.HasOne("LivrariaAPI.Model.Person", "editor")
                        .WithMany()
                        .HasForeignKey("editorid");

                    b.Navigation("editor");
                });
#pragma warning restore 612, 618
        }
    }
}
