// <auto-generated />
using LivrariaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LivrariaAPI.Migrations
{
    [DbContext(typeof(LivrariaAPIContext))]
    [Migration("20210531030457_db2")]
    partial class db2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("LivrariaAPI.Model.Book", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("anoLancamento")
                        .HasColumnType("int");

                    b.Property<long>("editor")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.Property<int>("pages")
                        .HasColumnType("int");

                    b.Property<decimal>("value")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id");

                    b.ToTable("book");
                });

            modelBuilder.Entity("LivrariaAPI.Model.Person", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("address")
                        .HasColumnType("longtext");

                    b.Property<string>("firstName")
                        .HasColumnType("longtext");

                    b.Property<string>("gender")
                        .HasColumnType("longtext");

                    b.Property<string>("lastName")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("person");
                });
#pragma warning restore 612, 618
        }
    }
}
